let musicList = [
    {
        id: 1,
        name: "Tai Vi Sao - MCK",
        artist: "MCK",
        img: "tai-vi-sao",
        src: "tai-vi-sao",
        lyric: [
            'Tại vì sao (yeah-eh) cảm xúc kia quay về? (Woah-oh-oh-oh)',
            'Là tại ai (yeah) đã khiến anh như vậy? (No-oh-oh)',
            'Một điều mà anh đã biết trước rằng là chỉ cần còn khoảng cách sẽ không thấy nhớ nhau',
            'Nhưng mà em đã lỡ lưu son của em (yeah) lên bức tranh anh tô màu',
            'Vậy thì giờ anh muốn ở bên em thật lâu bởi vì nàng là người làm trái tim anh thấy bớt đau',
            'Baby, em cứ giữ đi anh không cần đâu (woah-oh-oh-woah-oh)',
            'Và young boy cô đơn anh cũng muốn được yêu (okay)',
            'Baby, tin anh đi, anh không nói điêu',
            'Đề nghị nàng hãy bỏ ngay đi cho anh thói kiêu',
            'Và lắng nghe con tim anh nếu muốn được chiều',
            'Và nếu em là fire thì anh là nước',
            'Bởi vì khi ta gặp nhau thì ta sẽ dập nhau',
            'Cùng trao nhau tình yêu qua nụ hôn thật lâu',
            'Làm phai đi vệt son anh không muốn đậm màu',
            'Và đếm ba con số one, two, three',
            'Và nếu em không vui thì em cứ đi',
            'Vậy anh không muốn giữ đâu, anh ngu gì',
            'Và cũng đừng gọi tìm anh lúc em thấy suy',
            'Vì anh vẫn okay khi anh một mình',
            'Kiểm soát được tâm trí khi anh nhớ em',
            'Và giờ thì anh đã biết cách yêu bản thân mình',
            'Để không một lần nào lỡ hẹn',
            'Sẽ có những lúc anh đi quên lối về',
            'Thì liệu nàng còn vẫn muốn nắm lấy tay anh?',
            'Chỉ cần vài vệt son lướt lên trên đôi môi kề',
            'Cảm xúc ấy cứ thế vây quanh',
            'Bước xuống dưới phố khi không còn bóng người',
            'Bởi vì anh đi lang thang khi cô đơn lẻ loi',
            'Vào màn trời đêm đen ngỡ rằng em thấy rồi (oh-oh-oh-oh)',
            'Tại vì sao (tại vì sao, yeah) cảm xúc kia quay về? (Cảm xúc ấy, woah-oh-oh-oh)',
            'Vậy là tại ai (là tại ai, yeah) đã khiến anh như vậy? (Khiến anh như vậy, woah-oh-oh-oh)',
            'Có nuối tiếc khi...',
            'Em cứ đổ tại duyên số cho anh được chạm mặt',
            'Nếu biết sẽ đau khi thật lòng',
            'Liệu có vì một hình bóng mà đem lòng tin vào tình yêu phai màu?',
            'Bởi vì em (em, em), mắt em (mắt em)',
            'Chỉ toàn là màu xanh của tình yêu làm cho anh lại tưởng đại dương bên thềm (ooh-ooh, yeah)',
            'OK, khi (khi) thấy em (thấy em)',
            'Là cảm xúc chạm vào nhau vì muốn tận hưởng ngày trôi êm đềm',
            '(Có nuối tiếc khi...)',
            'Và nếu anh biết trước anh đã chẳng như thế',
            'Yeah baby, em không thích những thứ sâu cay',
            'But I thought that you were my baby',
            'Ta đã cùng nhau mơ về thứ sau này',
            'Và nếu anh biết trước anh sẽ không như thế',
            'Liệu em có còn giữ được niềm tin',
            'Để anh không còn lang thang đi kiếm tìm?',
            'Để đời mình được dựng thành một cuốn phim?',
            'Quãng ngày buồn',
            'Và có lẽ anh đã hơi dại dột',
            'Baby, anh hơi ngại rồi',
            'Chắc có lẽ anh tém lại thôi',
            'Bởi vì nàng là người thật đáng chờ đợi',
            'Em ơi, hãy mau mở lời',
            'Cho qua đi niềm đau ở đời',
            'Sao giờ đây con tim vỡ đôi?',
            'Tại vì sao (tại vì sao, yeah) cảm xúc kia quay về? (Woah-oh-oh-oh)',
            'Vậy là tại ai (là tại ai, yeah) đã khiến anh như vậy? (Khiến anh như vậy, woah-oh-oh-oh)',
            'Tại vì sao (tại vì sao, yeah, ooh-ooh-ooh-ooh) cảm xúc kia quay về? (Cảm xúc kia quay về, woah-oh-oh-oh)',
            'Vậy là tại ai (là tại ai, yeah) đã khiến anh như vậy? (Woah-oh-oh-oh)',
            'Sẽ có phút giây gần nhau',
            'Sẽ có phút giây gần nhau (phút giây)',
            'Ooh-ooh-ooh-ooh-ooh-ooh',
        ],
    },
    {
        id: 2,
        name: "Chi mot dem nua thoi - MCK",
        artist: "MCK",
        img: "chi-mot-dem-nua-thoi",
        src: "chi-mot-dem-nua-thoi",
        lyric: [
            'Chỉ một đêm nữa thôi',
            'Chỉ một đêm nữa thôi',
            'Chỉ một đêm nữa thôi',
            '(Louder, louder)',
            'Chỉ một đêm nữa thôi',
            'Lướt đi hơi nhanh trên con xe không phanh, đôi khi lòng mình lẻ loi',
            'Âm thanh vang lên ngay ở trong tai nghe, và tình yêu thì đã lên ngôi',
            'Nhìn đêm trôi gần sát bên tôi, chạm vào em và đưa sát lên môi',
            'Mọi buồn đau rồi sẽ quên thôi, yeah',
            'Là tại vì hình bóng của em giờ đang ở trong đầu (yeah, yeah, yeah)',
            'Và anh đã thức biết bao nhiêu là đêm dài mong cầu (yeah, yeah, yeah)',
            'Không cần phải nói mà sao vẫn cứ hiểu thấu lòng nhau (yeah)',
            'Same frequency, I don\'t wanna let you go',
            'Yeah, anh không muốn thức dậy (chỉ một đêm nữa thôi)',
            'Yeah, anh muốn chìm trong đôi mắt nàng (chỉ một đêm nữa thôi)',
            'Cạm bẫy vẫn đang xung quanh em (chỉ một đêm nữa thôi)',
            'But you got it, got it, got it, girl (one, two, three, go, okay)',
            'DCOD life, yeah, chân em mang Nike Low, yeah',
            'You gotta pick a side, yeah, eeny, miny, moe',
            'Mình cùng ngồi ngắm trăng tàn ở Sài Gòn hai giờ đêm (gad damn)',
            'Henni làm mắt ai mờ thêm, yeah, sau đêm nay xem là ai ở bên',
            'Cuốn một điếu thật to (yeah), bọn anh châm với Thành Draw (yeah)',
            'Bọn anh muốn có thật là nhiều tiền (woah), and we\'re gon\' make some more (yeah)',
            'A-C-I-D, gang, gang, 350 (350)',
            'Lúc đó nhìn em thật đẹp, that\'s everything I know',
            'Rồi mình xuống phố khi đang lên đồ, bầu trời nhiều sao mà đêm nay vẫn tối đen',
            'Nào là cạm bẫy, nào là thiên đường, nhưng mà tại sao trong tim anh có mỗi em',
            'Và chẳng còn biết được đâu là đêm và ngày, nếu cứ tiếp tục trên đà này',
            'I\'m so gonna fucking, fucking, fucking, fucking, fucking, fall in love with you',
            'Yeah, anh không muốn thức dậy (chỉ một đêm nữa thôi)',
            'Yeah, anh muốn chìm trong đôi mắt nàng (chỉ một đêm nữa thôi)',
            'Cạm bẫy vẫn đang xung quanh em (chỉ một đêm nữa thôi)',
            'But you got it, got it, got it, girl (yeah)',
            'Cho em nắm tay anh một chút được không? (Pretty boy)',
            'Những điều sau đây xin phép được nói thật lòng (tell me, baby)',
            'Em không chắc em đang cảm thấy điều gì nhưng mà nhớ anh',
            'Chỉ muốn thấy anh ngay ở bên cạnh (I wanna see you right here)',
            'You got me trippin\' như bị rơi vào tròng (yeah, yeah, trippin\', trippin\')',
            'Nhưng em không thấy bản thân mình đang đề phòng, no',
            'You make me feel safe, rằng mọi thứ sẽ okay khi ở trong vòng tay anh, yeah',
            'Em cũng không muốn thức dậy (yeah, anh cũng không muốn thức dậy)',
            'Mặc kệ thời gian để nó chảy (mặc kệ thời gian đi baby)',
            'Xung quanh là bao nhiêu cạm bẫy',
            'But we got it, yeah',
        ],
    },
    {
        id: 3,
        name: "Em con nho anh khong - Hoang Ton ft Koo",
        artist: "Hoang Ton",
        img: "em-con-nho-anh-khong",
        src: "em-con-nho-anh-khong",
        lyric: [
            'Em còn nhớ anh không? Em còn nhớ anh không? ',
            'Từ lâu anh đã quen mình phải cô đơn',
            'Vì anh không thể tìm được một ai hơn (hơn là em)',
            'Ngày em đi trong anh biết bao nỗi buồn',
            'Rồi lâu lâu nước mắt trong lòng cứ tuôn',
            'Không phải anh yếu đuối đâu',
            'Cũng không phải là lần cuối đâu',
            'Bao ngày ta đã dối nhau anh cố vứt đi nỗi sầu',
            'Đêm ngày vẫn luôn hát ca nhưng trong lòng như muốn nát ra',
            'Khi mà em đã cố xem anh như một người lạ',
            'ĐK:',
            'Trong phút giây mỏi mệt... anh nhận ra anh nhớ em',
            'Cố giấu đi từng đêm chỉ làm cho khóe mi cay thêm',
            'Cứ thế anh lặng nhìn giây phút em lặng thinh',
            'Quay bước đi mà chẳng nghĩ suy dù em biết anh cần gì',
            'Không biết bây giờ này... Em liệu đang đi với ai',
            'Không biết bây giờ đây anh là người đúng hay đã sai?',
            'Chỉ là nỗi nhớ, chỉ là dĩ vãng, chỉ là câu hát anh viết dẫu đã muộn màng',
            'Em còn nhớ anh không?',
            '(Đêm rồi từng đêm cô đơn càng nhiều thêm',
            'Những nốt nhạc này vang lên từ con tim luôn tìm về em) x2',
            'Rap:',
            'Em có đang nhớ anh không em có đang giận anh không',
            'Em có đang một mình giữa những đám đông rồi cô đơn trong vô vọng',
            'Ba giờ sáng, Sài Gòn khuya chẳng còn ai muốn nghe anh kể',
            'Are you okey hay em vẫn vậy, vẫn có ai đó đón đưa trên đường về',
            'Anh cứ bước mà chẳng biết đi đâu, sao bây giờ ta không còn vì nhau',
            'Nỗi buồn của anh to như sao hỏa chỉ cần thấy em cười là anh không sao cả',
            'Nếu ban đêm em gặp ác mộng do ban ngày em không đủ suy nghĩ',
            'Em có đang cần một ai đó khác không hay là say mèm rồi bên cạnh tri kỷ',
            'Em có đang nhớ anh không em có đang giận anh không',
            'Em có đang một mình giữa những đám đông rồi cô đơn trong vô vọng',
            'Nếu như nghĩ về đôi ta làm em cảm thấy mệt mỏi',
            'Nếu như ngày giờ trôi qua em phải làm việc từ sớm đến tận tối',
            'Thì nhớ phải cười thật tươi, vì lúc em cười thật đẹp',
            'Đừng tìm hình bóng của một ai khi con tim em đang chật hẹp.',
        ],
    },
    {
        id: 4,
        name: "Khi Con Mo Dan Phai - Tez",
        artist: "Tez",
        img: "khi-con-mo-dan-phai",
        src: "khi-con-mo-dan-phai",
        lyric: [
            'Mọi đau đớn người tự vượt qua thôi',
            'Vì giờ đây hai ta chẳng thể đến bên nhau',
            'Ở phía trước từng đoạn đường anh đi',
            'Rồi sẽ có ai thay em nắm tay anh',
            '[Verse 1:]',
            'Bên em là quãng đời hạnh phúc nhất',
            'Chung giấc mơ chung đôi ta chung giường',
            'Nhưng cơn mơ nào cũng phải thức giấc',
            'Ta vẫn tiến về phía trước',
            'Nhưng không chung một cung đường',
            'Ta của quá khứ sẽ ghét ta của hiện tại',
            'Đau thương yêu dấu đều giấu kín ở đáy sâu',
            'Bao câu hẹn ước giờ chỉ còn trong điện thoại',
            'Nhưng nếu ngày bên nhau lặp lại',
            'Anh cũng sẽ chẳng thay đổi nó đâu',
            'Em dạy anh biết cách yêu bản thân mình',
            'Dạy anh tự tha thứ cho lỗi lầm ngày xưa anh gây',
            'Dạy anh thật lòng với từng cung bậc cảm xúc',
            'Và dạy anh cách thẳng thắng để nói ra lời chia tay',
            'Vậy nên cứ mỉm cười',
            'Vì tương lai chúng ta sẽ còn tốt hơn',
            'Mọi thứ sẽ ổn thôi trên con đường mình tới',
            'Hạnh phúc nhất là không còn nhau ở trong tay',
            'Nhưng vẫn giữ ở trong tim để bước trên hành trình mới',
            '[Hook:]',
            'Mọi đau đớn người tự vượt qua thôi',
            'Vì giờ đây hai ta chẳng thể đến bên nhau',
            'Ở phía trước từng đoạn đường anh đi',
            'Rồi sẽ có ai thay em nắm tay anh',
            'Khi cơn mơ kia dần phai ai ai ai ai',
            'Ta đâu bên nhau ngày mai ai ai ai ai',
            'Khi cơn mơ kia dần phai ai ai ai ai',
            'Anh vẫn sẽ phải alright ai ai ai ai',
            '[Verse 2:]',
            'Chúng ta giờ chỉ còn là hình bóng',
            'Hai đứa trẻ tự rời khỏi nơi mình sống',
            'Đôi tay mơ xây dựng gia đình nhỏ',
            'Giờ lặng buông nhau rời bỏ cánh cửa, tim tự mình đóng',
            'Từng ước cùng bước lên mọi sân khấu cùng nhau',
            'Kỷ niệm ngày đó nghĩ lại chỉ thêm thương tổn',
            'Khi giờ ở trên sân khấu lớn nhất đời anh',
            'Thiếu vắng bóng hình em nhưng anh muốn nói là "Dương ổn"',
            'Mong em trở thành người phụ nữ độc lập vui vẻ không giận dữ',
            'Và luôn được thoải mái với cảm xúc của chính mình',
            'Đương nhiên anh cũng sẽ phải cố gắng thật thành công',
            'Để có trở thành người đàn ông quyết đoán nhiều hơn',
            'Ngay cả ở trong phần tính tình',
            'Mong sau này gặp lại ta có thể nói lời cảm ơn',
            'Vì tháng ngày sưởi ấm con tim nhau qua đêm lạnh',
            'Cảm ơn em vì cho anh biết tình yêu là buông bỏ',
            'Biết rằng mình vẫn sẽ tốt khi không còn ai bên cạnh',
            '[Hook:]',
            'Dù cho em không thể bước tiếp bên anh',
            'Mong rằng người đừng quá đau buồn',
            'Rồi sẽ có ai kia cùng anh tới sẻ chia',
            'Và lấy đi hết bao nước mắt trong tim',
            'Còn lại mọi đau đớn người tự vượt qua thôi',
            'Vì giờ đây hai ta chẳng thể đến bên nhau',
            'Ở phía trước từng đoạn đường anh đi',
            'Rồi sẽ có ai thay em nắm tay anh',
            'Khi cơn mơ kia dần phai ai ai ai',
            'Ta đâu bên nhau ngày mai ai ai ai ai',
            'Khi cơn mưa kia dần phai ai ai ai ai',
            'Anh vẫn sẽ phải alright ai ai ai ai',
            'Khi cơn mơ kia dần phai ai ai ai ai',
            'Ta đâu bên nhau ngày mai ai ai ai ai',
            'Khi cơn mơ kia dần phai ai ai ai ai',
            'Anh vẫn sẽ phải alright ai ai ai ai',
            'Mọi đau đớn người tự vượt qua thôi',
            'Vì giờ đây hai ta chẳng thể đến bên nhau',
            'Ở phía trước từng đoạn đường em đi',
            'Rồi sẽ có ai thay anh nắm tay em​',
        ],
    },
    {
        id: 5,
        name: "Ai cung co the la quan quan - Dick",
        artist: "Dick",
        img: "ai-cung-co-the-la-quan-quan",
        src: "ai-cung-co-the-la-quan-quan",
        lyric: [
            'Sau những ngày buồn sẽ là một mớ niềm vui',
            'Và đi theo sau đó là.. vài khoản nợ',
            'Trước khi mình chóng già',
            'Cứ bôn ba, miền núi miền xuôi',
            'Còn hơn là đứng yên, một chỗ rồi hoảng sợ',
            'Có quá nhiều trách nhiệm, chướng ngại, vướng bận',
            'Thôi mà cứ yên tâm đi, rồi hào quang sẽ đến mà',
            'Một bài nhạc tích cực trong vòng chung kết dành tặng cho quý khán giả',
            'Và cả những người thương kẻ mến',
            'Khắp nơi đổ về xem ai mới là Quán quân',
            'Kể cả những cô chú đang bán bưng',
            'Họ thức dậy mưu sinh khi trời sáng trưng',
            'Vậy tự hỏi rằng? Họ không xứng đáng sao',
            'Viết một bài nhạc vui để cuộc đời này xua tan bao ưu phiền',
            'Khiến nó thành động lực để sáng thức dậy, làm và có tiền',
            'Ai cũng có thể là quán quân',
            'Chiến thắng bản thân là chiến thắng chính mình',
            'Leo núi cao thì đau mắt cá chân',
            'Lội xuống sông sâu thì mới biết dính sình (lầy)',
            'Nếu như không có màn đêm',
            'Thì làm sao thấy được những vì sao',
            'Dù bạn là ai và làm nghề gì cũng được',
            'Chỉ cần tử tế và yêu đời',
            'Thì cùng đưa tay thật cao',
            'Bởi vì còn có những quán quân ngoài kia mặt lấm lem bùn',
            'Mà đôi khi ta bị che đi tầm mắt',
            'Có ai đâu hay rằng một ngày sẽ đứng nơi đây',
            'Chỉ để được nói “Hãy sống vui lên bạn ơi”',
            'Ai cũng có thể trở thành quán quân',
            'Bởi bạn xứng đáng sau những tháng năm',
            'Tự do là thứ không thể ngán chân',
            'Ta thường bị đau đầu vì những chuyện không đâu',
            'Chưa đi hết quả đất hình cầu, sao hiểu được biển rộng sông sâu',
            'Anh lớn lên từ một thành phố, có nhiều con ngõ thông giao',
            'Những ước mơ tuy không cánh, bay như ngọn cỏ bông lau',
            'Oh ah, mới ngày nào tiếng chửi của ba và má',
            'Mua cây micro dỏm về “Yeah yeah!”',
            'Tập tành theo hiphop đi la cà',
            'Bây giờ mới hiểu cảm giác của những đứa con xa nhà',
            'Và nếu như là ngày đó mà mình từ bỏ thì chắc là đã không có',
            'Thằng Hiếu của ngày hôm nay rồi',
            'Chỉ tiếc là dòng thời gian này không thể đợi một ai cả',
            'Lớn hơn trưởng thành không còn mấy chỗ mà anh em mình thường hay ngồi',
            'Tất cả, người em anh đều xứng đáng',
            'Sống chung một thời,',
            'Cùng sinh lão (bệnh tử), đồng cam (công khổ)',
            'Thành công rồi sẽ tới vào một ngày không xa nữa',
            'Ngày mà đủ cơm ba bữa, tặng thêm một bông hoa nữa',
            '(Hãy sống vui lên bạn ơi)',
            'Quán quân cho người công nhân lao động',
            'Hăng say, bác dân phòng, chú công an mang mũ',
            'Quán quân cho ông bố đơn thân đang nuôi con,',
            'Và những người mẹ già sau bao nhiêu năm lam lũ',
            'Anh đến cuộc thi với một thông điệp tốt đẹp,',
            'Biết mình biết ta, và cũng chẳng muốn tranh đua',
            'Đối với anh, em cũng là quán quân',
            'Vô địch thiên hạ với cái món canh chua',
            'Không cần đính đá, không cần danh hiệu',
            'Chỉ cần mỗi ngày kiếm đều đều 5 triệu',
            'Lời đàm tiếu, anh lại bỏ ngoài tai',
            'Sống như nào cũng được, miễn là nó hợp vai',
            'Trên truyền hình công chiếu, ai cũng biết rằng',
            'Anh trình không thiếu',
            'TEAM BRAY, ai là bạn anh Hiếu',
            'Mặc áo hiệu anh bán, let’s go',
            'Bởi vì còn có những quán quân ngoài kia mặt lấm lem bùn',
            'Mà đôi khi ta bị che đi tầm mắt',
            'Có ai đâu hay rằng một ngày sẽ đứng nơi đây',
            'Chỉ để được nói “Hãy sống vui lên bạn ơi”',
            'Na na na ná ni na nà',
            'Na na na nà na nì ná',
            'Na na ná ni na nà',
            '(Chỉ để được nói “Hãy sống vui lên bạn ơi”)',
            'Ya và đây cũng là bài hát cuối cùng của hành trình này',
            'Hy vọng tất cả mọi người sẽ là quán quân của cuộc đời mình',
            'Và đây là Huỳnh Công Hiếu – Team Bray!',
        ],
    },
    {
        id: 6,
        name: "Rolling Down - Captain",
        artist: "Captain",
        img: "rolling-down",
        src: "rolling-down",
        lyric: [
            'Chỉ là một cơn gió',
            'Thoáng qua',
            'Giữa phố xá nơi giọt sương màu hạ',
            'Chỉ là ước muốn bé đi',
            'Để cho nước mắt vơi bớt trên khóe mi',
            'Đằng sau bờ vai',
            'Là những bước chân chậm rãi',
            'Trôi đi giữa không gian buồn thiu khờ dại',
            'Còn lại suy và tư, trong bức tranh mẹ giữ',
            'Chỉ mong sao thời gian không khiến ta tự sự',
            'And I\'m rolling rolling rolling down',
            'Con đã rơi vào rơi vào trong bức tranh huyền ảo',
            'Rolling rolling rolling rolling down',
            'Con đã rơi vào rơi vào',
            'Con mong muốn mama quay lại lúc xưa',
            'Vu vơ mấy câu ca vào lúc mưa',
            'Hòa vào màn đêm tối',
            'Cùng đoạn đường quen lối',
            'Mà sao khung thời gian trôi đi thật vội',
            'Và rồi thanh xuân bay đi qua thật là mau',
            'Ây mẹ không thu âm mà thu mình trong lâu ngày',
            'Vì sau này mong tô cơm đầy',
            'Là thứ khiến cho mama lại cau mày',
            'Cũng chỉ vì nuôi con lớn',
            'Dậy thật là sớm',
            'Làm làm làm và làm thật nhiều việc hơn',
            'Trời nóng bức mẹ lại lo toan',
            'Cho những đứa con thêm khô khan',
            'Và con luôn mong về quê',
            'Vì đó là nơi không chật chỗ để xe',
            'Vì đó là nơi mà mẹ chở mẹ che',
            'Hai ba bài nhạc của con có mẹ mở mẹ nghe',
            'And I\'m rolling rolling rolling down',
            'Con đã rơi vào rơi vào trong bức tranh huyền ảo',
            'Rolling rolling rolling rolling down',
            'Con đã rơi vào rơi vào',
            'Đến một ngày con nhận ra',
            'Khôn và lớn đó là khi',
            'Là khi ăn đòn của mẹ sẽ không khóc',
            'Nhưng sẽ khóc khi mà thấy mẹ ướt đôi hàng mi',
            'Con biết con với bố không nói chuyện được lâu',
            'Hai người đàn ông nhưng cái nhìn ngược nhau',
            'Và bố dạy con không được run',
            'Vì giun thì chỉ đem đi buộc mồi câu',
            'Và con đã làm việc này hằng đêm',
            'Con bán cả máy tính, 6 giờ thay đồ làm thêm',
            'Thời gian không có đủ cho việc ngủ',
            'Nên là con không có bạn hay là bè đến và làm quen',
            'Thằng Duy vẫn còn mệt',
            'Nhưng mà nó sẽ không đau',
            'Tên lửa cần nhiên liệu để bay tới mong cầu',
            'Với con thì phần quà lớn nhất',
            'Không phải quán quân mà chỉ đơn giản là một cái xoa đầu',
            'From mama',
            'Nhiều chông gai con bước đi qua',
            'Dù ra sao vẫn luôn nhớ nhà',
            'Mẹ cũng chẳng muốn mong thêm điều chi',
            'Nhiều khi cũng chỉ muốn quay trở về',
            'Khi mà khi mà khi mà mama mới tròn 20',
            'Ước mơ là đứng ở đây',
            'Dù cho hồi đó ngày hai lần cơm nguội',
            'Và bây giờ thì đến lượt con',
            'Sẽ có những đồ ăn thật ngon',
            'Tô cho đẹp thêm màu son',
            'Viết giấc mơ mai sau',
            'Vì giờ sẽ có ma ma đứng chờ',
            'And I\'m rolling rolling rolling down',
            'Con đã rơi vào rơi vào trong bức tranh huyền ảo',
            'Rolling rolling rolling rolling down',
            'Con đã rơi vào rơi vào',
            'Sẽ có những giấc mơ không nằm trong tầm với',
            'Con đã rơi vào rơi vào trong bức tranh huyền ảo',
            'Rolling rolling rolling rolling down',
            'Con đã rơi vào rơi vào',
            'Hey y eey he aay he aay.',
        ],
    },
    {
        id: 7,
        name: "Tay-Lai Pr0 - Double2T & JustaTee",
        artist: "Double2T & JustaTee",
        img: "tay-lai-pro",
        src: "tay-lai-pro",
        lyric: [
            'Có bông sen nở giữa bùn,',
            'Vươn mình để một ngày tỏa hương bay đi xa',
            'Có đôi chân đất trên bản',
            'Mang nhạc người đồng bào để một ngày vang xa',
            'Băng qua bùn lầy, vươn mình từ 0 lên thành 100',
            'Bước lên đây tỏa sáng',
            '“Thanh âm trên miền núi” khắp nơi đang bật vang',
            'Cho họ biết rằng đây là ai',
            'Double2T on the mic',
            'Thì “Juss Juss” cũng phải like',
            'Bật con beat rap, ca trên đồi, ngồi đi vần',
            'Và anh dùng melodic kể chuyện làm nhạc trên bản',
            'Và nếu như mà em thích nghe thì nó là đơn giản',
            'Outfit thổ cẩm oai hơn cả việc mang vàng',
            'Lên núi săn mây ngỡ như đang trên thiên đàng',
            'Mời em ngao du trên thuyền này',
            'Tóc em đen tuyền này',
            'Anh giỏi giã gạo tay truyền chày',
            'Anh có mấy thằng bạn lai Tây',
            'Tay huyền Tày',
            'Thay vì bảo không có thì anh nói là mí mì',
            'Người miền núi chất rời bản làng để đi thi',
            'Múa khèn trên beat drill trên TV',
            'Hai chấm ngoặc ngoặc. Ỏ Hi Hi',
            'Nhưng anh quăng thính đừng lo chạy ngay',
            'Người đời nhìn anh tựa hai cành cây',
            'Boi bản chất, gió thổi là bay',
            'Lên đây, tỏa sáng cùng Boi Hồ Tây',
            'Không như mỹ nam The Face,',
            'Anh chỉ có khuôn mặt lai Tây (Tây Hồ)',
            'Không có bắp tay nhiều cơ,',
            'Anh chỉ đóng tune và làm thơ',
            'Em chê dáng anh nhìn hoi,',
            'Nhưng nghe tiếng ca thì “mơi”',
            'I’mma Superstar Hoi, in your heart',
            'Từ đồng xanh lên núi non, lốp ta tuy non',
            'Hoi vẫn lái bon bon',
            'Như nonstop, anh make some noise cả thôn xóm',
            'Chỉ cần hai nốt sol la sol la sol',
            'Hoi mãi luôn giòn',
            'Má anh dặn không cần phải tạo nét',
            'Bố anh dạy ra đường phải thật đét',
            'Tránh năng lượng kiêu ngạo và đừng phét',
            'Đừng wanna be, wanna be, wanna be.',
            'Má anh dặn không cần phải tạo nét',
            'Bố anh dạy ra đường phải thật đét',
            'Tránh năng lượng kiêu ngạo và đừng phét',
            'Đừng wanna be, wanna be, wanna be.',
            'Không cần phải tự dát vàng lên người',
            'Vì chất từ bên trong anh phát sáng',
            'Thành quả là xác đáng, bên dưới chân còn cát bám',
            'Đi lên bằng tài năng anh bù vóc dáng',
            'Vượt qua mọi rào cản để tiến vào Chung kết',
            'Nhạc nào anh cũng cân hết',
            'Ba năm chờ thi Rap Việt',
            'Mười năm theo đuổi thứ mình thích',
            'Tăng ga thẳng về vạch đích',
            'Chuyển từ 0 lên 100',
            'Anh chỉ có khuôn mặt lai Tây (Tây Hồ)',
            'Không hot boy HongKong,',
            'Anh vẫn lái đưa nàng sang sông',
            'Không có bắp tay nhiều cơ,',
            'Anh chỉ đóng tune và làm thơ',
            'Em chê dáng anh nhìn hoi,',
            'Nhưng nghe tiếng ca thì “mơi”',
            'I’mma Superstar Hoi, in your heart',
            'Từ đồng xanh lên núi non, lốp ta tuy non',
            'Hoi vẫn lái bon bon',
            'Như nonstop, anh make some noise cả thôn xóm',
            'Chỉ cần hai nốt sol la sol la sol',
            'Hoi mãi luôn giòn',
            'Má anh dặn không cần phải tạo nét',
            'Bố anh dạy ra đường phải thật đét',
            'Tránh năng lượng kiêu ngạo và đừng phét',
            'Đừng wanna be, wanna be, wanna be.',
            'Má anh dặn không cần phải tạo nét',
            'Bố anh dạy ra đường phải thật đét',
            'Tránh năng lượng kiêu ngạo và đừng phét',
            'Đừng wanna be, wanna be, wanna be.',
            'Có bông sen nở giữa bùn,',
            'Vươn mình để một ngày tỏa hương bay đi xa',
            'Má anh dặn không cần phải tạo nét',
            'Bố anh dạy ra đường phải thật đét',
            'Tránh năng lượng kiêu ngạo và đừng phét',
            'Đừng wanna be, wanna be, wanna be.',
            'Má anh dặn không cần phải tạo nét',
            'Bố anh dạy ra đường phải thật đét',
            'Tránh năng lượng kiêu ngạo và đừng phét',
            'Đừng wanna be, wanna be, wanna be, wanna be, wanna be, wanna be.​',
        ],
    },
    {
        id: 8,
        name: "Nguoi duoc chon - Dick & 24k.Right",
        artist: "Dick & 24k.Right",
        img: "nguoi-duoc-chon",
        src: "nguoi-duoc-chon",
        lyric: [
            'Anh mong em có được',
            'Tất cả những thứ từ trước giờ mà em muốn',
            'Anh mong em giữ được',
            'Tất cả anh em kể cả khi em đi xuống',
            'Anh mong em nhớ được',
            'Em có một gia đình hạnh phúc mỗi khi bước chân ra cửa',
            'Kể cả là khi em ghét anh, anh vẫn mong em ấm no không phải lo cơm ngày ba bữa',
            'Anh mong em đi được trên lửa',
            'Anh mong em thành công hơn nữa',
            'Anh mong em chuẩn không cần sửa',
            'Anh mong anh em mình sống dai',
            'Anh mong em nhai sạch chướng ngại như cơm bữa',
            'Vì sẽ không có ai yêu em hơn là chính em',
            'Và sẽ có một ngày khán giả không còn tới xem.',
            'Và nếu tới ngày đó, em vẫn còn là chính em',
            'Và nếu tới ngày đó, em phải luôn là chính em',
            'Vì anh Mất 30 năm, để biết mình nhỏ bé',
            'Học cách nói chuyện nhỏ nhẹ',
            'Hiểu được nếu muốn được thấu hiểu thì việc đầu tiên cần làm là lắng nghe',
            'Anh vẫn luôn luôn trung cầu sự hoàn hảo',
            'Để rồi cảm thấy thất vọng về bản thân',
            'Anh không phải B Ray cũng không còn là Bảo Anh không hãnh diên về cả hai dù một lần',
            'Nhưng mà đêm nay, chúng ta tới đây là để ăn mừng',
            'Lăng nghe những tiếng pháo nổ, vang lừng đi khắp quanh vùng',
            'Không cần bằng rừng, không cần săn lùng',
            'Không cần tranh phần, không cần canh chừng',
            'Nâng ly cho những người được chọn',
            'Những người anh hùng không cần danh phận',
            'Từ trong bóng tối',
            'Những đứa con tìm đường ra ánh sáng',
            'Khối óc, trái tim',
            'Vì ta xứng đáng, xứng đáng',
            'Anh mong anh mong',
            'Rằng anh sẽ biết cách sống',
            'Và mặt trời đang cao dần lên',
            'Soi vào giấc mơ hôm nào',
            'Cùng nâng ly mừng',
            'Cuz we found da new champion tonight..',
            'Mở con mắt ra xem',
            'Xem ai là người được chọn',
            'Cáp show với cả gang',
            'Gan to cùng với đồng bọn',
            'Như nhà ảo thuật gia,',
            'Hồ biến hater trở thành fans',
            'Where they at?',
            'I thought you wanted beef',
            'Where they at?',
            'I thought you wanted beef',
            'Where they at?',
            'I thought you wanted beef',
            'guess not, keep it humble, take a seat',
            'Không muốn mất thời gian vì chẳng ai cho anh lựa chọn',
            'Âm Nhạc từ lòng đất..',
            'Quấn dây leo, đi lên tận ngọn',
            'Underdog, tụi anh đến đây để lật kèo',
            'Bắc, Trung, Nam toàn người xa lạ nhưng sau tất cả anh em cột chèo',
            'Sống ở Sài Gòn, mắc bao nhiêu khúc xương để trở lên lớn tầm này',
            'Trân trọng những con người đã đi qua',
            'Trước mặt của nó là bao nhiêu tượng đài',
            'Cảm ơn – biết ơn – chắp tay – cúi đầu',
            'Một vợ hai con ba lầu bốn bánh',
            'Ngày mai anh em phải giàu',
            'Nhiều người nhìn thấy ở trên tivi',
            'Và họ gọi cho má anh và nói là mừng cho anh',
            'Với cái tuần suất mà tụi anh đang làm việc',
            'Ai là người được chọn, không rảnh để tranh giành',
            'Kiếm thật nhiều lúa cho vào ngân hàng',
            'Không phàn nàn và chăm chỉ hơn',
            'Truyền trái bóng cho em Right',
            'Luôn thận trọng ở trong mọi vận động',
            'Phá lưới vào cung thành',
            'Trap hay Oldschool boombap rap hát',
            'Đều là chung ngành',
            'Nghỉ một nhịp..',
            'Lấy hơi rồi tung hoành',
            'Trước khi có Việt Rap',
            'Trước cả đống kiệt tác',
            'Shout out Khanh Nhỏ và Thái VG mang rap về nước',
            'GVR, LadyKillah AERap & GODZ',
            'SSR, SSS, FSR & GFamily',
            '95G, G5R, DCOD, Undre the hood',
            'Tây Nguyên Sound, EvB, BCTM đang bay cao vút',
            'Where they at?',
            'I thought you wanted beef',
            'Where they at?',
            'I thought you wanted beef',
            'Where they at?',
            'I thought you wanted beef',
            'I guess not, keep it humble, take a seat',
            'TV phát sóng cậu bé vàng làm chủ đề bàn tán cho',
            'những cậu bé mạng',
            'Không thể đoán điều anh sẽ làm',
            'Khi thấy anh tự tin di chuyển thật khế khàng',
            'Họ thích thô bạo hay nhẹ nhàng',
            'Right ballin so hard nó không hề dề dàng',
            'Cất lại một chút của vẻ vang, bởi vì ai cũng biết cuộc vui nào cũng sẽ tàn',
            'Mr. Nam châm hút nón vàng',
            'Mỗi lần Right đi lên sân khấu làm tim các em lại xốn xang',
            'Anh muốn đóng vai người đầu bếp',
            'Nhưng ho muốn thử anh như một món ăn',
            'Anh Hiếu chuyền cho anh trái bóng để Right ghi thêm một đống bàn',
            'Để anh cũng biết, khi con beat cần giải quyết, Right. sẽ ngồi mải miết',
            'Flow vần chảy xiết, Masew quả này nảy phết, bật lên mấy em lại nhảy miết',
            'Đứng ngồi không yên, không một ai là không miên man từ nhà hát đến công viên',
            'Em bảo Right trông duyên, nên Right kéo kính lên và đưa em về Long Biên',
            'Người được chọn may mắn cho ai đã thấy',
            'Anh chỉ làm đúng việc mà giờ ai cũng biết rõ ràng Right quá cháy',
            'Sáng hơn cả kim cương có người nhắc khéo hôm nay Right đẹp trai quá đấy',
            '0 1 2 3 4 anh hỏi bé fan em sinh năm 2k mấy',
            'Em bảo Oh không nói em hơi bad bad bad bad',
            'Từ phòng thu, sân khấu anh làm họ hét hét hét hét',
            'Loking cool, on point',
            'Trông anh fresh fresh fresh fresh',
            'Wanna know who the chosen one thì xem xem xem xem',
            'Where they at?',
            'Got a couple haters như gió thoáng mây bay',
            'Where they at?',
            'Wanna know who the chosen one thì xem xem xem xem',
            'Where they at?',
            'Got a couple haters như gió thoáng mây bay',
            'Where they at?',
            'Socola kẹo mút, nhưng lại có vị cay cay',
            'Nghe nó cứ bị hay hay',
            'Anh Tee vặn vài nút tự nhiên là nghe nó tây tây',
            'Baby I’mma go big',
            'Để anh lo con hook, là mọi thứ cứ là okay',
        ],
    },
    {
        id: 9,
        name: "Mien Che - Tez & BigDady",
        artist: "Tez & BigDady",
        img: "mien-che",
        src: "mien-che",
        lyric: [
            '(Em yêu Bigdaddy)',
            'Em muốn tăng áp cứ xem anh diễn đê',
            'Nghe anh một phát đung đưa là miễn về',
            'Em không quan sát, hôm sau lại tiếc ghê',
            'Vì một khi anh rap thì đương nhiên là miễn chê',
            'Em muốn tăng áp cứ xem anh diễn đê',
            'Nghe anh một phát đung đưa là miễn về',
            'Em không quan sát, hôm sau lại tiếc ghê',
            'Vì một khi anh rap thì đương nhiên là miễn chê',
            'Mê chứ mê chứ chê là chê làm sao được',
            'Bigdaddy catchy anh rap ở dưới là khán giả bao thuộc',
            'Mê chứ mê chứ chê là chê làm sao được',
            'Out trình từ vibe tới outfit nên anh có nhiều fan nhìn ao ước',
            'Máy quay lia vào anh flow các em khen hay nhức người',
            'Cho anh xin lỗi nha hai năm qua anh rất lười',
            'Rap Việt mùa 3 anh xuất hiện, cười rất tươi',
            'Cứ bình tĩnh cho em biết thế nào là lễ hội',
            'Tez ơi làm cốc trà đá',
            'Lên thi rap bốc vào nha',
            'Ngọt giọng, bùi tai chị em muốn thơm vào má',
            'Team này toàn tiểu phẩm, nhưng vào việc thì là kĩ tính',
            'Team này cũng chơi kiểu Mỹ, nhưng mà là kiểu Mỹ Đình',
            'Đứng hết cả lên, đứng hết cả lên nào',
            'Có bạn có bè thì cứ rủ thêm vào',
            'Đây là sân chơi mà em đến là miễn về',
            'Rap Việt mùa 3 cứ phải gọi là miễn chê',
            'Em muốn tăng áp cứ xem anh diễn đê',
            'Nghe anh một phát đung đưa là miễn về',
            'Em không quan sát, hôm sau lại tiếc ghê',
            'Vì một khi anh rap thì đương nhiên là miễn chê',
            'Em muốn tăng áp cứ xem anh diễn đê',
            'Nghe anh một phát đung đưa là miễn về',
            'Em không quan sát, hôm sau lại tiếc ghê',
            'Vì một khi anh rap thì đương nhiên là miễn chê',
            'Lời chê anh bát ngát, trên các diễn đàn',
            'Như ngồi trà đá, anh nói là miễn bàn',
            'Nở nụ cười thiện chí, của người làm nghề diễn thuê',
            'Nhưng âm nhạc này miễn phí nên vui lòng là miễn chê',
            'Các em bé cứ chê anh nhạt chê anh đen rồi chê anh xấu giai',
            'Giờ anh rap chất, bảnh bao rồi cả tấu hài',
            'Anh vẫn kiên cường thay đổi khiến những người đó một lần nữa mê',
            'Cứ review lại update nên tiếp tục chê nữa đê',
            'Tai anh ngập tràn tiếng hét của người yêu thương họ khen',
            'Họ muốn được thấy anh thắng như là fan của Ngọt band',
            'Cảm ơn mỗi ngày những người ở bên những giờ phút thăng trầm',
            'Cho anh kho báu mà anh tìm kiếm là cái cúp trong lòng',
            'Đặt trụ vững vàng, chân bước cần gì phải nhón',
            'Câu chuyện nổi bật, họ đâu còn gì phải nhấn',
            'Chiếm mọi ánh nhìn đến khi không còn gì phải lấn',
            'Một đạp (chọn) băng về đích, đầu trần anh cần gì phải nón',
            'Em muốn tăng áp cứ xem anh diễn đê',
            'Nghe anh một phát đung đưa là miễn về',
            'Em không quan sát, hôm sau lại tiếc ghê',
            'Vì một khi anh rap thì đương nhiên là miễn chê',
            'Em muốn tăng áp cứ xem anh diễn đê',
            'Nghe anh một phát đung đưa là miễn về',
            'Em không quan sát, hôm sau lại tiếc ghê',
            'Vì một khi anh rap thì đương nhiên là miễn chê',
            'Em muốn tăng áp cứ xem anh diễn đê',
            'Nghe anh một phát đung đưa là miễn về',
            'Em không quan sát, hôm sau lại tiếc ghê',
            'Vì một khi anh rap thì đương nhiên là miễn chê',
            'Em muốn tăng áp cứ xem anh diễn đê',
            'Nghe anh một phát đung đưa là miễn về',
            'Em không quan sát, hôm sau lại tiếc ghê',
            'Vì một khi anh rap thì đương nhiên là miễn chê.',
        ],
    },
    {
        id: 10,
        name: "Hong lau mong - MC.ILL",
        artist: "MC.ILL",
        img: "hong-lau-mong",
        src: "hong-lau-mong",
        lyric: [
            'Dạy miễn phí không cần tiền bạc, dù biết súc vật càng lúc càng lười',
            'Dạy lại lũ súc sinh cách rap chuẩn, và dạy thêm chúng nó cách làm người',
            'Ghi chép rồi cút về nhà mà đọc, lũ mọi rợ học thức không sâu rộng',
            'Ngói nát đừng cố làm Giả Bảo Ngọc, lũ chúng mày đừng có mơ Hồng Lâu Mộng',
            'Dạy miễn phí không cần tiền bạc, dù biết súc vật càng lúc càng lười',
            'Dạy lại lũ súc sinh cách rap chuẩn, và dạy thêm chúng nó cách làm người',
            'Ghi chép rồi cút về nhà mà đọc, lũ mọi rợ học thức không sâu rộng',
            'Ngói nát đừng cố làm Giả Bảo Ngọc, lũ chúng mày đừng có mơ Hồng Lâu Mộng',
            'Tao phải cân nhắc liệu có nên rep Pjpo, vì dạy súc sinh chắc gì sẽ có ích',
            'Một phần vì tao cũng xem xét nghĩ lo, fan nó cắm cờ mất con mẹ nó nick',
            'Cái cuộc sống này nó cứ rình giông gió, bất công là thứ duy nhất nó luôn thừa',
            'Thằng Choi đã đấu với tứ linh trong đó, còn tao đang đấu với một con đuông dừa',
            'Viết status gáy như Chi Pu, nhạc ra được một nhúm văn còm',
            'Quẩy sớm ăn gì hả các bạn? Địt con mẹ mày quẩy sớm ăn lồn',
            'Mất bao lâu mới rặn ra cái bài nhạc như buồi người ta nghe qua loa rồi tắt',
            'Phải chăng mày bận casting diễn viên Star Wars cho vai Jabba the Hutt?',
            'Mày đòi địt mẹ ai, khi con cặc mày thụt trong mỡ và đéo biết tìm đâu',
            'Con ghệ mày bật đèn pin mò mẫm dưới từng lá mỡ, gọi đó là vạch lá tìm sâu',
            'Bọn tao chẳng dám đe dọa hay bạo lực, vì dân bây giờ rất là khôn',
            'Họ thừa biết con súc sinh như mày khi chết thì đéo có đất mà chôn',
            'Nhưng nếu nó chết thì cũng đừng hoảng hốt, chẳng có việc gì phải sợ lo',
            'Chúng mày có thể tìm xác Pjpo trong gói hạt nêm từ thịt Knorr',
            'Chúng mày có thể chắc chắn rằng, Pjpo ra đi với một tấm lòng son',
            'Xưa nay các cụ đã dạy: “Con lợn có béo thì lòng mới ngon”',
            'Dạy miễn phí không cần tiền bạc, dù biết súc vật càng lúc càng lười',
            'Dạy lại lũ súc sinh cách rap chuẩn, và dạy thêm chúng nó cách làm người',
            'Ghi chép rồi cút về nhà mà đọc, lũ mọi rợ học thức không sâu rộng',
            'Ngói nát đừng cố làm Giả Bảo Ngọc, lũ chúng mày đừng có mơ Hồng Lâu Mộng',
            'Dạy miễn phí không cần tiền bạc, dù biết súc vật càng lúc càng lười',
            'Dạy lại lũ súc sinh cách rap chuẩn, và dạy thêm chúng nó cách làm người',
            'Ghi chép rồi cút về nhà mà đọc, lũ mọi rợ học thức không sâu rộng',
            'Ngói nát đừng cố làm Giả Bảo Ngọc, lũ chúng mày đừng có mơ Hồng Lâu Mộng',
            'Fat joke mày trước, rebuttal mày sau, tao dạy lại chúng mày vài chiêu rap chiến',
            'Bây giờ đéo còn giữ lễ nữa, chỉ còn sự xúc phạm, cho tất cả những điều khác biến',
            'Tổ sư bố cái truyền thống làm đĩ, tự hào lồn gì cái mảnh đất nhiễu nhương',
            'Nghe miền Tây tao đéo thấy dễ thương, tao thấy con đĩ Ngọc Trinh là biểu tượng',
            'Dám mở mõm nói đến Cờ và rap, chẳng lẽ mày tình nguyện bị bắt sao',
            'Hưng Cao là Đế Thích của rap Việt, CAO KỲ mày đéo thể CAO KỲ bằng tao',
            'Khuôn mặt mày chỉ có cái TƯỚNG SĨ, mày là TƯỢNG gỗ mục tao ngả ra đốt',
            'Vì sinh ra đám mọt chỉ giỏi khoe XE PHÁO hoặc câu fame nhờ cái MÃ TỐT',
            'Đồ vô học câm mõm lại, tao đã im lặng, mày được thể lấn lướt làm càn',
            'Nếu tao có công ty chỉ đạo, thì công ty đó nó yêu nước đàng hoàng',
            'Phải bịa chuyện tao có công ty chỉ đạo, nói điêu có bao giờ mày mang hối lỗi?',
            'Nói tao bị ĐỨNG SAU GIẬT DÂY, rõ ràng con chó Kỳ đang nói DỐI/RỐI',
            'Mang văn cùn lý bịa bị vả vỡ mõm thì tao hỏi mày định ăn bằng gì?',
            'Hãy nhớ Quốc Ca được viết bởi VĂN CAO chứ nó đéo được viết bởi VĂN KỲ',
            'Mày là nỗi sỉ nhục của gia tộc, chẳng ai dám mang nỗi nhục này giãi bày',
            'Đến mức mẹ mày sẽ mát lồn rười rượi nếu ngày hôm đấy bà ấy sảy thai mày',
            'Dạy miễn phí không cần tiền bạc, dù biết súc vật càng lúc càng lười',
            'Dạy lại lũ súc sinh cách rap chuẩn, và dạy thêm chúng nó cách làm người',
            'Ghi chép rồi cút về nhà mà đọc, lũ mọi rợ học thức không sâu rộng',
            'Ngói nát đừng cố làm Giả Bảo Ngọc, lũ chúng mày đừng có mơ Hồng Lâu Mộng',
            'Dạy miễn phí không cần tiền bạc, dù biết súc vật càng lúc càng lười',
            'Dạy lại lũ súc sinh cách rap chuẩn, và dạy thêm chúng nó cách làm người',
            'Ghi chép rồi cút về nhà mà đọc, lũ mọi rợ học thức không sâu rộng',
            'Ngói nát đừng cố làm Giả Bảo Ngọc, lũ chúng mày đừng có mơ Hồng Lâu Mộng',
            'Bao năm tao mong đất Việt này hòa hợp, nhưng chúng mày khiến tao ngậm chặt hờn căm',
            'Nếu bảo vệ quê hương bị coi là hai mặt, thì tao xin tình nguyện làm hai mặt ngàn năm',
            'Tao tình nguyện làm kẻ phản diện, hiên ngang ngạo nghễ nhếch miệng cười đời',
            'Thằng HAI MẶT đưa mày lên tòa nhà cao nhất đất Việt, và biến mày thành NGƯỜI RƠI',
            'Chúng mày giỏi cả văn lẫn võ, lại cái bài dọa đánh coi mạng người rẻ như đinh vít',
            'Lỡ mà tao bị làm sao mà mày phải vào tù, hãy nói lời vĩnh biệt với trinh đít',
            'Chúng mày tài năng quá biến ảo thật tình nhận ra điều đó đã khiến tao giật mình',
            'Nào là photoshop với cắm cờ đối thủ, chúng mày mới xứng đáng là rapper lập trình',
            'Tao thương con mẹ mày thâm lồn, đã khổ sở lúc lâm bồn',
            'Đẻ ra đời thằng âm hồn, sớm bị tao bắt câm mồm',
            'Có thằng fan không thể giấu mối tình đồng tính với Pjpo',
            'Tên nó nói lên mong muốn cả đời được dính với “bi to”',
            'VD chết mới được khen bởi những đứa chửi lại thầy',
            'Địt con mẹ đồ súc vật là lời tao muốn gửi chúng mày',
            'VD bị đệ tử chửi, là truyền thống đó hả mày?',
            'Giờ VD thành lá chắn cho cái nòi giống chó phản thầy',
            'Dạy chúng mày và tất cả bọn phản thầy ở ba miền',
            'Môn Đạo Đức và nhân phẩm, chẳng cần dạy có ra tiền',
            'Nhục mạ đám vô liêm sỉ mà bọn mọi rợ tung hô',
            'Đánh như năm xưa Lý Mục giết 10 vạn rợ Hung Nô',
            'Đó là chút hy vọng của chúng mày sao?',
            'Vậy chúng mày óc cứt hay bẩm sinh chúng mày Down?',
            'Mấy thằng khả năng yếu mau mang cả chăn chiếu',
            'Bỏ nhà ra Punch Miếu dập đầu cúng thầy Cao',
            'Dạy miễn phí không cần tiền bạc, dù biết súc vật càng lúc càng lười',
            'Dạy lại lũ súc sinh cách rap chuẩn, và dạy thêm chúng nó cách làm người',
            'Ghi chép rồi cút về nhà mà đọc, lũ mọi rợ học thức không sâu rộng',
            'Ngói nát đừng cố làm Giả Bảo Ngọc, lũ chúng mày đừng có mơ Hồng Lâu Mộng',
            'Dạy miễn phí không cần tiền bạc, dù biết súc vật càng lúc càng lười',
            'Dạy lại lũ súc sinh cách rap chuẩn, và dạy thêm chúng nó cách làm người',
            'Ghi chép rồi cút về nhà mà đọc, lũ mọi rợ học thức không sâu rộng',
            'Ngói nát đừng cố làm Giả Bảo Ngọc, lũ chúng mày đừng có mơ Hồng Lâu Mộng',
        ],
    },
    {
        id: 11,
        name: "Van - 24k.Right ft.Huynh Tu, HIPZ",
        artist: "24k.Right",
        img: "van",
        src: "van",
        lyric: [
            'Có bàn chân lặng lẽ,',
            'Giữa dòng đời như nước cuốn.',
            'Chập chờn trắng đen không thể nhìn thấy đáy.',
            'Từ trong bão giông vẫn nghe tiếng gọi',
            'Right không còn đi bán đồ nữa rồi',
            'Nhưng nó vẫn đi chơi với cả một lũ tồi',
            'Quá nhiều lần nó đã bị lừa dối',
            'Cảm ơn chúa nó vẫn là thằng giữ lời',
            'Vẫn giao dịch với dealer địa phương',
            'Nên cái đ gì tao nói cũng là bịa luôn',
            'Trước khi họ gọi đó là hiện trường đấy là chỗ tao vẫn chất hàng chất hàng',
            'Hustler thì nhận ra hustler khi gặp nhau ngoài phố bọn tao hất hàm hất hàm',
            'Tao cố tránh xa khỏi va chạm dù những thằng là bạn tao nó rất là sẵn sàng',
            'Khi tao nói tao không làm nữa, anh em tao tham tiền chúng nó vẫn làm vẫn làm',
            'Nếu như họ không nhốt nó lại thì có lẽ bây giờ nó vẫn đang dẫn đoàn',
            'Lại 1 ngày ở bên trong thành phố, mấy thằng chó vẫn muốn nói không thành có',
            'Mấy em gái vẫn muốn biến tao thành bố, quỷ dữ vẫn muốn biến tao thành nó thành nó',
            'không thể chạy hệ điều hành đó, vẫn luôn thô lỗ với mấy em chảnh chó',
            'từng trong traphouse có biến lá cây thành giấy, trốn khỏi đó giờ tao biến chữ thành số',
            'man, nghe hơi đạo đức giả, tao nói mấy anh em thôi đừng bando',
            'không zích đội bóng này không bán độ, công ty đóng giao dịch mỗi tối lúc 8h',
            '24k dây chuyền khi nó bám cổ, 22 cân ở đó khi họ khám nhà',
            'Không biết nó sẽ nói gì với cán bộ, nó từng nói với tao sẽ dừng bán mà',
            'R k còn đi bán đồ nữa rồi nhưng fadil vẫn đóng như GTA',
            'Ném gói 3 như VBA',
            'có cả ke ta min MDMA',
            'VND trong DNA, lái máy bay VNA',
            'tiền mặt hoặc VNpay, tao phi trên dream n wave',
            'Mẹ tao không thích người tao đầy hình xăm',
            'Không đủ tiền đổ đầy 1 bình xăng',
            'Rời khỏi thành phố mang chỉ đủ tiền ăn',
            'Chờ may mắn cho 1 đường chuyền căng',
            'Trẻ tuổi và tao biết mình non dạ, chưa bao giờ chối bỏ tao đã sai lầm sai lầm',
            'Ồn ào hàng xóm sẽ gọi phường nên khi chia chác bọn tao silent silent',
            'Đừng hỏi tại sao tính bọn tao lại nóng thế',
            'Cảnh hành động không cần diễn viên đóng thế',
            'Mày ý kiến gì về âm nhạc của tao khi mày kiếm còn không bằng tiền của tao đóng thuế',
            'Nếu fan yêu tao thì tao cũng yêu họ vì khi bật nhạc tao họ thấy mình cũng giống thế',
            'Nếu tao yêu em, tao gọi em là cái cửa vì mấy thằng đấy đ có và tao đến để đóng bé',
            'Trong thành phố bọn tao pass cs cho mấy thằng vừa tỉnh ra, không phân biệt vùng miền',
            'Ham muốn sự tôn trọng, quyền lực và đàn bà cả 3 thứ đó chúng nó đều phải dùng tiền',
            'Khi 20 thằng trên xe và lạng lái đấy gọi là trạng thái tốt nhất đừng phiền',
            'Tao chỉ cúi đầu trước người đàn ông trên thánh giá và tao chỉ đánh cá với những thằng cùng thuyền',
        ],
    },
];
